# Задания на повторение материала

### Задание 1
Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [1]:
import numpy as np

In [2]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

### Задание 2
Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
mass = []
num = 0
for i in range(2,13):
    if 12 % i == 0:
        mass.append(a.reshape(i, int(12 / i)))
        print('Массив № ', num + 1)
        print(mass[num])
        num +=1

Массив №  1
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Массив №  2
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Массив №  3
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
Массив №  4
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
Массив №  5
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


### Задание 3
Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [4]:
mass2 = []
num = 0
for i in range(1,4):
    mass2.append(a.reshape(i + 1, -1))
    print('Массив № ', num + 1, ' - столбец=-1')
    print(mass2[num])
    num +=1
    if i < 3:
        mass2.append(a.reshape(-1, i))
        print('Массив № ', num + 1, ' - строка=-1')
        print(mass2[num])
        num +=1

Массив №  1  - столбец=-1
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Массив №  2  - строка=-1
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
Массив №  3  - столбец=-1
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Массив №  4  - строка=-1
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
Массив №  5  - столбец=-1
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


### Задание 4
Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [5]:
massive = np.random.randn(12,1)
print(massive)
print("Размерность: {}".format(a.ndim))

[[ 0.20233002]
 [-0.13759743]
 [-0.46145787]
 [-1.08186314]
 [ 0.6038865 ]
 [-0.02485492]
 [-0.11466446]
 [-0.19998985]
 [-0.56680542]
 [-0.22337402]
 [-0.11301127]
 [-0.43604906]]
Размерность: 1


**Ответ:**
Таким образом, можно.

### Задание 5
Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [6]:
b = np.random.randn(3, 4)
b

array([[-0.43721529, -0.38168546,  0.02267608,  1.50587505],
       [-0.18490699, -1.86096093, -1.04331271, -2.32396447],
       [ 0.06457239, -1.4556484 , -0.36453193,  0.67865254]])

In [7]:
b_1 = b.reshape(1, -1)
b_1

array([[-0.43721529, -0.38168546,  0.02267608,  1.50587505, -0.18490699,
        -1.86096093, -1.04331271, -2.32396447,  0.06457239, -1.4556484 ,
        -0.36453193,  0.67865254]])

In [8]:
b.size == b_1.size

True

In [9]:
b.size

12

### Задание 6
Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [10]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

### Задание 7
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [11]:
b = np.arange(20, 1, -2).reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [12]:
a == b

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [13]:
print("Размерность a: {}".format(a.ndim))
print("Форма a: {}".format(a.shape))

Размерность a: 1
Форма a: (10,)


In [14]:
print("Размерность b: {}".format(b.ndim))
print("Форма b: {}".format(b.shape))

Размерность b: 2
Форма b: (1, 10)


**Ответ:** Массивы a и b отличаются своей размерностью и формой.

### Задание 8
Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [15]:
size = 0
while size != 10:
    num_1 = np.random.randint(2, 11) # num_1 - число строк массива а
    if 10 % (2 * num_1 + 1) == 0:
        num_2 = int(10 / (2 * num_1 + 1)) # num_2 - число столбцов массивов
        a = np.zeros((num_1, num_2))
        b = np.ones((num_1 + 1, num_2))
        v = np.vstack((a,b))
        size = (2 * num_1 + 1) * num_2
        print('v.size = ', v.size)
        print(v)        

v.size =  10
[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


### Задание 9
Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?


In [16]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [19]:
B = A.dot(At)
print(B)
print('размер матрицы B =', B.shape)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
размер матрицы B = (4, 4)


In [20]:
B_det = np.linalg.det(B)
print('Определитель матрицы В =', B_det)

Определитель матрицы В = 0.0


**Ответ:** Матрица В - вырожденная, т.к. определитель матрицы равен нулю, а значит, у неё нет обратной матрицы.

### Задание 10
Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [21]:
np.random.seed(42)

### Задание 11
Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [22]:
c = np.random.randint(0, 16, (16, ))
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

### Задание 12
Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [23]:
C = c.reshape(4,4)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [24]:
D = B + C * 10
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [25]:
print('Определитель матрицы D =', np.linalg.det(D))
print('Ранг матрицы D =', np.linalg.matrix_rank(D))
D_inv = np.linalg.inv(D)
print('Матрица, обратная матрице D: \n', D_inv)

Определитель матрицы D = -28511999.999999944
Ранг матрицы D = 4
Матрица, обратная матрице D: 
 [[ 0.00935396  0.04486532  0.05897517 -0.07286055]
 [-0.01503577 -0.00122896 -0.00192971  0.00967873]
 [-0.00356692 -0.01782828 -0.04152146  0.04326178]
 [ 0.00909091 -0.00181818  0.01272727 -0.01090909]]


### Задание 13
Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.


In [26]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.]])

In [27]:
E = np.where(D_inv, B, C)
E

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])